### ISSUE TITLE
Play Queue Management

### ISSUE THREAD

**Issue by fow5040** [fow5040/Wox.Plugin.SpotifyPremium#1]
### Issue Description
Can't Modify the current play queue (add to queue, reset queue, etc.)

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [x] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [ ] Searching Spotify for albums, artists or songs

**Comment by fow5040** [comment]
The Spotify API currently doesn't support queue management: may be able to add once queue management is added:
https://github.com/spotify/web-api/issues/462

**Comment by rururux** [comment]
It looks like now can [add to queue](https://developer.spotify.com/documentation/web-api/reference/player/add-to-queue/).

**Comment by fow5040** [comment]
Great news - thanks @rururux. I'll add this functionality in at some point.

**Comment by rururux** [comment]
I'm looking forward to it.
thank you for good plugin😊

**Comment by fow5040** [comment]
UPDATE: New SpotifyAPI library is pretty drastically different from earlier version - will need to restructure a good bit of this plugin. See branch 'queue-management'

**Comment by fow5040** [comment]
Basic queue management is now implemented in the queue management branch - I want to clean up the code and refractor searching into one streamlined method before I re-release the plug in

**Comment by fow5040** [comment]
Code is merged, refactored, and re-released! You can reinstall Wox.SpotifyPremium (wpm install/uninstall) and the queue changes should be reflected.
