### ISSUE TITLE
Not every playlist is showing up

### ISSUE THREAD

**Issue by Kamefrede** [fow5040/Wox.Plugin.SpotifyPremium#3]
### Issue Description

As the name says, when typing sp playlist it only lists about half of the playlists it should, and searching for playlists that were not listed but that I'm following will result in the plugin saying it found no results.

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [ ] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [X ] Searching Spotify for albums, artists or songs

### Software Versions

Please fill in the following information:

- Spotify client version (`Help > About Spotify`): 1.1.30.658.gf13cde74
- Wox version (`Wox Settings > About`): 1.3.578

**Comment by fow5040** [comment]
Hey Kamefrede, I don't think I found a way to efficiently paginate the playlist results so it may be searching an incomplete subset of all accessible playlists. Let me investigate further.

**Comment by fow5040** [comment]
Hey Kamefrede - I'm not sure the best way to solve this in the meantime other than just having Wox pull a larger number of playlists. Currently I just grab 50, so I'll bump it up to grabbing up 500 user playlists. It's an arbitrary limit but I assume most standard users don't have 500+ Spotify Playlists... so it'll have to do

**Comment by fow5040** [comment]
~~Kamefrede I "updated" the SpotifyPremium from 1.0.0 to 0.9.1... can you uninstall and reinstall spotifyPremium and confirm the playlist(s) you were looking for show up now?~~

~~WPM uninstall Wox.SpotifyPremium~~
~~WPM install Wox.SpotifyPremium~~

Hold on - need to test more

**Comment by fow5040** [comment]
@Kamefrede Ok - it should be working now if you want to uninstall and reinstall the Plugin. The initial playlist request may take a while (like, more than 10 seconds) because it needs to cache images for your playlists, but after that it should return pretty quickly. Let me know if your experience is different

**Comment by Kamefrede** [comment]
Sp playlist shows me a bunch of playlist that aren't mine, could it be any chance showing me someone else's?

**Comment by Kamefrede** [comment]
Update: Yeah upon trying to see the devices available with sp device it shows me two that are not my devices

**Comment by fow5040** [comment]
I left my temporary token in the deployment package... 🤦‍♂️

Should be fixed now

**Comment by Kamefrede** [comment]
Seems to display all my playlists now so I'd call it fixed!

**Comment by fow5040** [comment]
Great! Thanks for working with me on this one.
