### ISSUE TITLE
Search Functionality Crippled

### ISSUE THREAD

**Issue by Iaotle** [fow5040/Wox.Plugin.SpotifyPremium#4]
### Issue Description

The search function often returns no results whatsoever. Have tried using both the provided and the private Client ID / Secret ID.
![image](https://user-images.githubusercontent.com/43072246/87623906-b81fd500-c726-11ea-83b8-0d0dc2b3f5f5.png)
![image](https://user-images.githubusercontent.com/43072246/87623878-accca980-c726-11ea-83ac-f07a9a441dfe.png)
![image](https://user-images.githubusercontent.com/43072246/87623847-9d4d6080-c726-11ea-98af-e30d64e36300.png)
![image](https://user-images.githubusercontent.com/43072246/87623923-c3730080-c726-11ea-8f78-942f544e187a.png)

### Functionality Affected
- [ ] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [x] Searching Spotify for albums, artists or songs

### Software Versions
- Spotify client version 1.1.36.734.g8731c306
- Wox version 1.4.1196

**Comment by fow5040** [comment]
Hey @Iaotle - I finally got around to fixing this and it looks like any URI with no artwork in Spotify (in this case, the Artist "Iron Mango"...) was throwing an exception. I modified my code to return a generic icon if artwork is missing. I'll merge the fix into master and re-release soon.

Also - would be happy to merge your .NET Core 3.1 changes to my plugin if it has been working fine for you.

Cheers

**Comment by Iaotle** [comment]
@fow5040 not sure what you mean about the .NET stuff. Plans to re-release anytime soon?

**Comment by fow5040** [comment]
@Iaotle Hey this is a bit late - I merged the small error handling fix to master so spotify artists with missing artwork (in this case, "Iron Mango") do not break the plugin.   

I can do a quick re-release now, but I plan to do a bigger rework with the updated SpotifyAPI.Web 6.2.0 Nuget package that enables queue management, among other things.

**Comment by fow5040** [comment]
Mislabeled the fix - 23dd81b9efbda6405e6df1851b40ee23d1f2dd29 solves this issue, not Issue #5

**Comment by Iaotle** [comment]
Cheers! Everything works! <3
