### ISSUE TITLE
Error when going to reuathorize API

### ISSUE THREAD

**Issue by llamapower13** [fow5040/Wox.Plugin.SpotifyPremium#5]
### Issue Description

downloaded plugin, typed SP to start, it said it needed to be reauthorized. Opened firefox and saw this 
![Screenshot 2020-10-21 163922](https://user-images.githubusercontent.com/73196018/96784852-ff6bd080-13bb-11eb-9b24-7cb812d47e05.png)

What should I do? Thanks

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [x ] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [ x] Searching Spotify for albums, artists or songs

### Software Versions

Please fill in the following information:

- Spotify client version (`Help > About Spotify`): 1.1.44.538.g8057de92 (Microsoft Store version)
- Wox version (`Wox Settings > About`): 1.4.1196

**Please also make sure you're running the latest version of Wox.Plugin.Spotify**

**Comment by fow5040** [comment]
Hi, can you go to `%appdata%\Wox\Plugins\Wox.SpotifyPremium-f5d10873-a69a-468b-b1a2-1a075a8dcb0d` and delete the `security.store` file, then see if the issue persist?

**Comment by techmaved** [comment]
I have the same problem, the deletion of the file doesn't solve the problem.

**Comment by fow5040** [comment]
mislabeled the fix - 23dd81b9efbda6405e6df1851b40ee23d1f2dd29 solves ISS #4, not this issue

**Comment by fow5040** [comment]
Closing for now until more users report the issue
